inventory:
    plugin: "NetBoxInventory2"
    options:
        nb_url: "http://localhost:8000"
        nb_token: "b2ed8d99d3f2453082f2c65e4503c953470d0883"
        defaults_file: "src/inventory/defaults.yaml"

runner:
    plugin: threaded
    options:
        num_workers: 10
