services:
  netbox:
    image: netbox:latest
    pull_policy: never
    ports:
      - 8000:8080
    build:
      context: .
      dockerfile: Dockerfile-Plugins
  netbox-worker:
    image: netbox:latest
    pull_policy: never
  netbox-housekeeping:
    image: netbox:latest
    pull_policy: never
